# Generated by Django 4.1.2 on 2022-11-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
