# Generated by Django 4.1.2 on 2022-11-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_counter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='counter',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='counter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
