# Generated by Django 4.1.2 on 2022-11-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('groups', '0002_remove_group_members_groupmembers_group_admins'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembers',
            unique_together={('group', 'member')},
        ),
    ]
