# Generated by Django 4.1.2 on 2022-11-21 10:28

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('groups', '0003_alter_groupmembers_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(default=groups.models.return_admin, through='groups.GroupMembers', to='users.member'),
        ),
    ]
