# Generated by Django 4.1.3 on 2023-01-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(to='groups.admin'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2023-01-15 13:01'),
        ),
    ]
