# Generated by Django 4.1.2 on 2022-11-25 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='admins',
        ),
    ]
