# Generated by Django 4.1.3 on 2023-01-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='groups',
        ),
        migrations.AlterField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(
                related_name='groups',
                to='groups.admin'
            ),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2023-01-17 15:01'),
        ),
    ]
