# Generated by Django 4.1.3 on 2023-01-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_members_alter_group_admins_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2023-01-24 10:01'),
        ),
    ]
