# Generated by Django 4.1.3 on 2023-02-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_alter_group_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='created_on',
            field=models.DateTimeField(default='2023-02-01 12:02'),
        ),
    ]
