---
name: Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install coverage
          python -m pip install flake8
      - name: Run Tests
        run: |
          python manage.py test
      - name: Coverage
        run: | 
          coverage run --source . manage.py test
          coverage report --fail-under 90
      - name: Coding Style
        run: |
          flake8 --exclude */migrations*